[build]
  command = "pnpm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--version"
  NEXT_PUBLIC_ECOSYSTEM_PROFILE = "nimiq"
  NEXT_PUBLIC_WALLET_ADAPTER = "nimiq"
  NEXT_PUBLIC_CHAIN_ID = "80002"
  NEXT_PUBLIC_RPC_URL_PUBLIC = "https://polygon-amoy.drpc.org"
  NEXT_PUBLIC_CHAIN_NAME = "Polygon Amoy"
  NEXT_PUBLIC_BLOCK_EXPLORER_URL = "https://amoy.polygonscan.com"
  NEXT_PUBLIC_NATIVE_CURRENCY_NAME = "POL"
  NEXT_PUBLIC_NATIVE_CURRENCY_SYMBOL = "POL"
  NEXT_PUBLIC_NATIVE_CURRENCY_DECIMALS = "18"
  NEXT_PUBLIC_PAYMENT_TOKEN_TYPE = "native"
  NEXT_PUBLIC_PAYMENT_TOKEN_ADDRESS = ""
  NEXT_PUBLIC_PAYMENT_TOKEN_SYMBOL = "MATIC"
  NEXT_PUBLIC_PAYMENT_TOKEN_DECIMALS = "18"
  NEXT_PUBLIC_TOURNAMENT_MANAGER_ADDRESS = "0xDD62224dF25ce7590d7E8502C3e6b237Ea91C1A4"
  NEXT_PUBLIC_MISSION_POOL_ADDRESS = ""
  NEXT_PUBLIC_ACTIVE_MISSION_ID = ""
  NEXT_PUBLIC_BACKEND_URL = "https://api.pinball.sportwarren.com"
  NEXT_PUBLIC_SCORE_PREFIX = "PINBALL_SCORE:v2"
  NEXT_PUBLIC_NIM_TREASURY_ADDRESS = "NQ88 8AG0 1CXT 9Y11 77FU L706 M1TA R1FC DNKU"
  NEXT_PUBLIC_NIM_ENTRY_FEE = "1"
