import type { Metadata, Viewport } from "next";
import { Providers } from "./providers";

// Absolute base for all metadata URLs (og:image etc.). Social crawlers require
// absolute URLs; without this, relative image paths resolve against localhost
// and no card renders. Override with the real deployed host via env.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://pinball.sportwarren.com";

const TITLE = "Kamikaze Ball — The World's First Verifiable Arcade";
const DESCRIPTION =
  "Drain-to-win pinball where the machine fights back. On-chain tournaments, provably fair scores, and a guardian AI that refuses to let the ball fall.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: TITLE, template: "%s · Kamikaze Ball" },
  description: DESCRIPTION,
  applicationName: "Kamikaze Ball",
  manifest: "/manifest.webmanifest",
  icons: {
    icon: "/icon-192.png",
    apple: "/apple-touch-icon.png",
  },
  openGraph: {
    type: "website",
    url: "/",
    siteName: "Kamikaze Ball",
    title: TITLE,
    description: DESCRIPTION,
    // The 1200×630 image is generated by app/opengraph-image.tsx; Next injects
    // og:image(+width/height/alt) from that file automatically.
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image falls back to the generated og:image.
  },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: "#0d0d1f",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
